### ISSUE TITLE
Removing stale bytecode fails with multiple workers in `mtest`

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1733]
I think there is a race-condition when two or more worker attempt to remove the same stale file:

```
WORKER1: Removing stale bytecode file /var/lib/jenkins/jobs/opengever.core/workspace/opengever/bumblebee/__init__.pyc
WORKER1: Traceback (most recent call last):
WORKER1:   File "bin/test", line 375, in <module>
WORKER5: Removing stale bytecode file /var/lib/jenkins/jobs/opengever.core/workspace/opengever/bumblebee/__init__.pyc
WORKER5: Traceback (most recent call last):
WORKER5:   File "bin/test", line 375, in <module>
WORKER5:     sys.exit(collective.xmltestreport.runner.run_internal(['-s', 'opengever', '--exit-with-status', '--auto-color', '--auto-progress', '--xml', '--package-path', '/var/lib/jenkins/jobs/opengever.core/workspace/opengever', 'opengever']))
WORKER5:   File "/var/lib/jenkins/zope/eggs/collective.xmltestreport-1.2.6-py2.7.egg/collective/xmltestreport/runner.py", line 72, in run_internal
WORKER1:     sys.exit(collective.xmltestreport.runner.run_internal(['-s', 'opengever', '--exit-with-status', '--auto-color', '--auto-progress', '--xml', '--package-path', '/var/lib/jenkins/jobs/opengever.core/workspace/opengever', 'opengever']))
WORKER1:   File "/var/lib/jenkins/zope/eggs/collective.xmltestreport-1.2.6-py2.7.egg/collective/xmltestreport/runner.py", line 72, in run_internal
WORKER5:     runner.run()
WORKER1:     runner.run()
WORKER1:   File "/var/lib/jenkins/zope/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 148, in run
WORKER1:     feature.global_setup()
WORKER1:   File "/var/lib/jenkins/zope/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/find.py", line 473, in global_setup
WORKER5:   File "/var/lib/jenkins/zope/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 148, in run
WORKER5:     feature.global_setup()
WORKER5:   File "/var/lib/jenkins/zope/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/find.py", line 473, in global_setup
WORKER1:     tests = find_tests(self.runner.options, self.runner.found_suites)
WORKER1:   File "/var/lib/jenkins/zope/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/find.py", line 160, in find_tests
WORKER1:     remove_stale_bytecode(options)
WORKER1:   File "/var/lib/jenkins/zope/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/find.py", line 366, in remove_stale_bytecode
WORKER5:     tests = find_tests(self.runner.options, self.runner.found_suites)
WORKER5:   File "/var/lib/jenkins/zope/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/find.py", line 160, in find_tests
WORKER1:     os.unlink(fullname)
WORKER5:     remove_stale_bytecode(options)
WORKER5:   File "/var/lib/jenkins/zope/eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/find.py", line 366, in remove_stale_bytecode
WORKER1: OSError: [Errno 2] No such file or directory: '/var/lib/jenkins/jobs/opengever.core/workspace/opengever/bumblebee/__init__.pyc'
WORKER1: 
WORKER5:     os.unlink(fullname)
WORKER5: OSError
WORKER5: : [Errno 2] No such file or directory: '/var/lib/jenkins/jobs/opengever.core/workspace/opengever/bumblebee/__init__.pyc'
WORKER1: TERMINATED with exitcode 1
WORKER5: TERMINATED with exitcode 1
```

This problem results in failed builds, this has already happened several times after we switched to ci-governor. I would suggest to remove stale bytecode in `bin/mtest` before starting the workers.

**Comment by phabegger** [comment]
@deiferni Ist dieser Issue noch aktuell? Die Testing-Infrastruktur wurde ja inzwischen stark verändert.

**Comment by deiferni** [comment]
Wurde mittlerweile behoben, siehe https://github.com/4teamwork/opengever.core/blob/master/bin/mtest#L43-L50
