### ISSUE TITLE
"Enable ftw keywordwidget for document metadata behavior." upgrade fails

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2823]
```
2017-04-06T10:28:00 ERROR ftw.upgrade FAILED
Traceback (most recent call last):
  File "/home/zope/eggs/ftw.upgrade-2.3.1-py2.7.egg/ftw/upgrade/jsonapi/plonesite.py", line 155, in _install_upgrades
    executioner.install_upgrades_by_api_ids(*api_ids)
  File "/home/zope/eggs/ftw.upgrade-2.3.1-py2.7.egg/ftw/upgrade/executioner.py", line 51, in install_upgrades_by_api_ids
    return self.install(data)
  File "/home/zope/eggs/ftw.upgrade-2.3.1-py2.7.egg/ftw/upgrade/executioner.py", line 38, in install
    self._upgrade_profile(profileid, upgradeids)
  File "/home/zope/eggs/ftw.upgrade-2.3.1-py2.7.egg/ftw/upgrade/executioner.py", line 90, in _upgrade_profile
    last_dest_version = self._do_upgrade(profileid, upgradeid) \
  File "/home/zope/eggs/ftw.upgrade-2.3.1-py2.7.egg/ftw/upgrade/executioner.py", line 129, in _do_upgrade
    step.doStep(self.portal_setup)
  File "/home/zope/eggs/Products.GenericSetup-1.7.4-py2.7.egg/Products/GenericSetup/upgrade.py", line 140, in doStep
    self.handler(tool)
  File "/home/zope/eggs/ftw.upgrade-2.3.1-py2.7.egg/ftw/upgrade/directory/wrapper.py", line 12, in upgrade_step_wrapper
    target_version=target_version)
  File "/home/zope/eggs/ftw.upgrade-2.3.1-py2.7.egg/ftw/upgrade/step.py", line 49, in __new__
    return obj()
  File "/home/zope/theta.4teamwork.ch/01-dev.onegovgever.ch-fd/src/opengever.core/opengever/dossier/upgrades/20170328131435_set_task_comment_permission/upgrade.py", line 11, in __call__
    ['opengever_dossier_workflow'], reindex_security=False)
  File "/home/zope/eggs/ftw.upgrade-2.3.1-py2.7.egg/ftw/upgrade/step.py", line 449, in update_workflow_security
    updater.update(workflow_names, reindex_security=reindex_security)
  File "/home/zope/eggs/ftw.upgrade-2.3.1-py2.7.egg/ftw/upgrade/workflow.py", line 156, in update
    for obj in self.lookup_objects(types):
  File "/home/zope/eggs/ftw.upgrade-2.3.1-py2.7.egg/ftw/upgrade/workflow.py", line 165, in lookup_objects
    brains = tuple(catalog.unrestrictedSearchResults(query))
  File "/home/zope/eggs/collective.indexing-2.0b1-py2.7.egg/collective/indexing/monkey.py", line 89, in unrestrictedSearchResults
    processQueue()
  File "/home/zope/eggs/collective.indexing-2.0b1-py2.7.egg/collective/indexing/queue.py", line 39, in processQueue
    processed = queue.process()
  File "/home/zope/eggs/collective.indexing-2.0b1-py2.7.egg/collective/indexing/queue.py", line 165, in process
    util.reindex(obj, attributes)
  File "/home/zope/eggs/collective.indexing-2.0b1-py2.7.egg/collective/indexing/indexer.py", line 80, in reindex
    reindex(obj, attributes)
  File "/home/zope/eggs/collective.indexing-2.0b1-py2.7.egg/collective/indexing/indexer.py", line 57, in reindex
    op(obj, attributes or [])
  File "/home/zope/theta.4teamwork.ch/01-dev.onegovgever.ch-fd/src/opengever.core/opengever/base/monkey/patches/cmf_catalog_aware.py", line 77, in reindexObject
    return original_reindexObject(self, idxs)
  File "/home/zope/eggs/Products.CMFCore-2.2.7-py2.7.egg/Products/CMFCore/CMFCatalogAware.py", line 88, in reindexObject
    catalog.reindexObject(self, idxs=idxs)
  File "/home/zope/eggs/Products.CMFCore-2.2.7-py2.7.egg/Products/CMFCore/CatalogTool.py", line 301, in reindexObject
    self.catalog_object(object, uid, idxs, update_metadata)
  File "/home/zope/eggs/Products.CMFPlone-4.3.2-py2.7.egg/Products/CMFPlone/CatalogTool.py", line 353, in catalog_object
    update_metadata, pghandler=pghandler)
  File "/home/zope/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/ZCatalog/ZCatalog.py", line 476, in catalog_object
    update_metadata=update_metadata)
  File "/home/zope/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/ZCatalog/Catalog.py", line 360, in catalogObject
    blah = x.index_object(index, object, threshold)
  File "/home/zope/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/PluginIndexes/common/UnIndex.py", line 216, in index_object
    res += self._index_object(documentId, obj, threshold, attr)
  File "/home/zope/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/PluginIndexes/KeywordIndex/KeywordIndex.py", line 62, in _index_object
    self.insertForwardIndexEntry(kw, documentId)
  File "/home/zope/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/PluginIndexes/common/UnIndex.py", line 193, in insertForwardIndexEntry
    indexRow = self._index.get(entry, _marker)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
Result: FAILURE
```

**Comment by deiferni** [comment]
Current theory: The new widget now stores values as `utf-8` whereas the old widget stored them as `unicode`. `KeywordIndex` can't deal with that.
