### ISSUE TITLE
Test isolation broken for the sablon template test

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#2939]
```
Error in test test_download_sablon_template (opengever.meeting.tests.test_download_sablon_template.TestSablonTemplateDownloadView)
Traceback (most recent call last):
  File "/home/joni/koodaus/git/opengever.core/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/joni/koodaus/git/opengever.core/eggs/ftw.testbrowser-1.23.1-py2.7.egg/ftw/testbrowser/__init__.py", line 40, in test_function
    return func(self, *args, **kwargs)
  File "/home/joni/koodaus/git/opengever.core/opengever/meeting/tests/test_download_sablon_template.py", line 23, in test_download_sablon_template
    browser.find('label_download').click()
AttributeError: 'NoneType' object has no attribute 'click'
```

It seems we missed at least one pdfconverter test leak somewhere as this consistently trips up on the copy download availability where `bin/test` is run for the whole test suite.

Should have been fixed with 4teamwork/opengever.core/pull/2914, but this is still happening.

**Comment by phgross** [comment]
Seems to be solved, not flared up for over 6 months.
