### ISSUE TITLE
IProtectDossier breaks dossier edit and detail views

### ISSUE THREAD

**Issue by bierik** [4teamwork/opengever.core#3624]
```
Traceback (most recent call last):
  File "/Users/kbieri/.buildout/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/Publish.py", line 138, in publish
    request, bind=1)
  File "/Users/kbieri/.buildout/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/mapply.py", line 77, in mapply
    if debug is not None: return debug(object,args,context)
  File "/Users/kbieri/.buildout/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/Publish.py", line 48, in call_object
    result=apply(object,args) # Type s to step into published object.
  File "/Users/kbieri/.buildout/eggs/plone.autoform-1.6.2-py2.7.egg/plone/autoform/view.py", line 45, in __call__
    self._update()
  File "/Users/kbieri/.buildout/eggs/plone.autoform-1.6.2-py2.7.egg/plone/autoform/view.py", line 67, in _update
    group.update()
  File "/Users/kbieri/.buildout/eggs/z3c.form-3.2.11-py2.7.egg/z3c/form/group.py", line 52, in update
    self.updateWidgets()
  File "/Users/kbieri/.buildout/eggs/z3c.form-3.2.11-py2.7.egg/z3c/form/group.py", line 48, in updateWidgets
    self.widgets.update()
  File "/Users/kbieri/.buildout/eggs/z3c.form-3.2.11-py2.7.egg/z3c/form/field.py", line 277, in update
    widget.update()
  File "/Users/kbieri/.buildout/eggs/ftw.keywordwidget-1.3.6-py2.7.egg/ftw/keywordwidget/widget.py", line 145, in update
    super(KeywordWidget, self).update()
  File "/Users/kbieri/.buildout/eggs/z3c.form-3.2.11-py2.7.egg/z3c/form/browser/select.py", line 51, in update
    super(SelectWidget, self).update()
  File "/Users/kbieri/.buildout/eggs/z3c.form-3.2.11-py2.7.egg/z3c/form/browser/widget.py", line 171, in update
    super(HTMLFormElement, self).update()
  File "/Users/kbieri/.buildout/eggs/z3c.form-3.2.11-py2.7.egg/z3c/form/widget.py", line 234, in update
    super(SequenceWidget, self).update()
  File "/Users/kbieri/.buildout/eggs/Products.CMFPlone-4.3.15-py2.7.egg/Products/CMFPlone/patches/z3c_form.py", line 46, in _wrapped
    return update(self)
  File "/Users/kbieri/.buildout/eggs/z3c.form-3.2.11-py2.7.egg/z3c/form/widget.py", line 132, in update
    self.value = converter.toWidgetValue(value)
  File "/Users/kbieri/.buildout/eggs/z3c.form-3.2.11-py2.7.egg/z3c/form/converter.py", line 307, in toWidgetValue
    for entry in value:
TypeError: 'NoneType' object is not iterable
```

This only happens on dossiers generated by initcontent.

Steps to reproduce:

- Setup new site
- Open a dossier generated by initcontent (Jahresdossier for example)
- Go to `Aktionen` -> `Eigenschaften`

**Comment by elioschmutz** [comment]
It seems that you haven't run buildout.

You still run on `ftw.keywordwidget V1.3.6`, the new IProtectDossier feature requires `V1.4.1`.
