### ISSUE TITLE
A mock test fails when the unit test layer is run in isolation

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#3876]
`bin/test --layer zope.testrunner.layer.UnitTests`

```
Failure in test test_participation_with_handler (opengever.dossier.tests.test_participation.TestParticipationHanlder)
Traceback (most recent call last):
  File "/Users/joni/.homebrew/var/pyenv/versions/2.7.14/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/joni/koodaus/git/opengever.core/eggs/mocker-1.1.1-py2.7.egg/mocker.py", line 149, in test_method_wrapper
    result = test_method()
  File "/Users/joni/koodaus/git/opengever.core/opengever/dossier/tests/test_participation.py", line 45, in test_participation_with_handler
    self.assertEquals(handler.get_participations(), [peter, ])
  File "/Users/joni/.homebrew/var/pyenv/versions/2.7.14/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/joni/.homebrew/var/pyenv/versions/2.7.14/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: <mocker.Mock object at 0x10a851510> != [<opengever.dossier.behaviors.participation.Participation object at 0x10a78ae60>]
```

**Comment by Rotonen** [comment]
A bit more curious:

Passes:
`bin/test --layer UnitTest --layer AnnotationLayer`

Fails:
`bin/test --layer UnitTest`

Passes:
`bin/test --layer UnitTest -m opengever.dossier`
