### ISSUE TITLE
Flaky test failures related to language selector viewlet

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#3995]
🚧 Placeholder issue to reference issue # from code, more details to come 🚧 

Currently we're getting some **flaky test failures** related to the **language selector viewlet**. Haven't been able to reproduce those locally.

Some of the tests that rely on the language selector viewlet fail (seemingly randomly) because an exception happens during rendering of the language selector viewlet (`plone.app.i18n.locales.languageselector`):

---

![language_selector_failure](https://user-images.githubusercontent.com/405124/36379717-f3e3613e-157f-11e8-97a9-7445f1acfc6f.png)

---

Example:
https://ci.4teamwork.ch/builds/147573/tasks/232383

Traceback when attempting to render the language selector viewlet:
```
Error in test test_supports_translated_title_xxx (opengever.contact.tests.test_contactfolder.TestContactFolder)
Traceback (most recent call last):
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/var/lib/jenkins/zope/eggs/ftw.testbrowser-1.29.5-py2.7.egg/ftw/testbrowser/__init__.py", line 42, in test_function
    return func(self, *args, **kwargs)
  File "/var/lib/jenkins/workspace/opengever.core-weight-5/opengever/contact/tests/test_contactfolder.py", line 94, in test_supports_translated_title_xxx
    print langsel.render()
  File "/var/lib/jenkins/zope/eggs/zope.browserpage-3.12.2-py2.7.egg/zope/browserpage/simpleviewclass.py", line 44, in __call__
    return self.index(*args, **kw)
  File "/var/lib/jenkins/zope/eggs/Zope2-2.13.26-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/var/lib/jenkins/zope/eggs/Zope2-2.13.26-py2.7.egg/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/var/lib/jenkins/zope/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 126, in pt_render
    raise PTRuntimeError(str(self._v_errors))
   - Warning: Compilation failed
   - Warning: exceptions.ImportError: cannot import name NotFound
PTRuntimeError: ['Compilation failed', 'exceptions.ImportError: cannot import name NotFound']

```

**Comment by jone** [comment]
Auf CI reproduziert: https://ci.4teamwork.ch/builds/151102/tasks/238903
1/6 fails bis jetzt

**Comment by jone** [comment]
I wasn't able to reliable reproduce the problem so that I could debug it.
I tried to reproduce it on the jenkins master server on a separate checkout.
I ran `bin/mtest` in a loop for hours now and it didn't occur.
I'm not sure at this point how I could pin point the problem.

**Comment by Rotonen** [comment]
Leave `bin/mtest -j24` running over the weekend in a loop on both CI servers?

**Comment by jone** [comment]
Yeah we could do that. I ran it in a screen and passed `-D` to `bin/test` so that it would set a pdb on error. Although all skipIf-decorators need to be removed as this throws a tracaback..

**Comment by Rotonen** [comment]
Do we just close this at this point?

**Comment by deiferni** [comment]
ok 👍
