### ISSUE TITLE
Issues with some BTrees in upgrade step to fix broken references

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#4074]
The [upgrade step to fix broken references](https://github.com/4teamwork/opengever.core/blob/dd120be5ffa2bd06909ff8af9654d30d45f7a3e5/opengever/core/upgrades/20180306101228_fix_relation_catalog_references/upgrade.py#L14-L46) failed on `03-gever-stabs-test` like this:

```
2018-03-16T11:36:28 INFO ftw.upgrade UPGRADE STEP opengever.core:default: Fix relation catalog references.
------
2018-03-16T11:36:28 ERROR ftw.upgrade FAILED
Traceback (most recent call last):
  File "/home/zope/eggs/ftw.upgrade-2.11.0-py2.7.egg/ftw/upgrade/jsonapi/plonesite.py", line 158, in _install_upgrades
    executioner.install_upgrades_by_api_ids(*api_ids)
  File "/home/zope/eggs/ftw.upgrade-2.11.0-py2.7.egg/ftw/upgrade/executioner.py", line 57, in install_upgrades_by_api_ids
    return self.install(data)
  File "/home/zope/eggs/ftw.upgrade-2.11.0-py2.7.egg/ftw/upgrade/executioner.py", line 43, in install
    self._upgrade_profile(profileid, upgradeids)
  File "/home/zope/eggs/ftw.upgrade-2.11.0-py2.7.egg/ftw/upgrade/executioner.py", line 106, in _upgrade_profile
    last_dest_version = self._do_upgrade(profileid, upgradeid) \
  File "/home/zope/eggs/ftw.upgrade-2.11.0-py2.7.egg/ftw/upgrade/executioner.py", line 145, in _do_upgrade
    step.doStep(self.portal_setup)
  File "/home/zope/eggs/Products.GenericSetup-1.8.8-py2.7.egg/Products/GenericSetup/upgrade.py", line 166, in doStep
    self.handler(tool)
  File "/home/zope/eggs/ftw.upgrade-2.11.0-py2.7.egg/ftw/upgrade/directory/wrapper.py", line 13, in upgrade_step_wrapper
    target_version=target_version)
  File "/home/zope/eggs/ftw.upgrade-2.11.0-py2.7.egg/ftw/upgrade/step.py", line 49, in __new__
    return obj()
  File "/home/zope/03-gever-stabs-test/src/opengever.core/opengever/core/upgrades/20180306101228_fix_relation_catalog_references/upgrade.py", line 26, in __call__
    if self.has_broken_references(btree):
  File "/home/zope/03-gever-stabs-test/src/opengever.core/opengever/core/upgrades/20180306101228_fix_relation_catalog_references/upgrade.py", line 42, in has_broken_references
    pickler.dump(btree)
SystemError: error return without exception set
Result: FAILURE
```

The immediate issue being that the check to detect broken references attempts to pickle the BTree to find out whether it contains references to removed interfaces, but only expects a `cPickle.PicklingError`, nothing else.

In this case we got a `SystemError: error return without exception set` however.

Investigating this in debug mode yielded the following:

The problem can apparently be reproduced with both BTrees that are looked at in the upgrade step, 'to_interfaces_flattened' and 'from_interfaces_flattened':

```
>>> from opengever.maintenance import dm
>>> from zc.relation.interfaces import ICatalog
>>> from zope.component import getUtility
>>> import cPickle
>>> import StringIO
>>>
>>> dm()
INFO: Using Plone Site 'stabs'.
>>> catalog = getUtility(ICatalog)
>>> btree = catalog._name_TO_mapping['to_interfaces_flattened']
>>>
>>> pickler = cPickle.Pickler(StringIO.StringIO())
>>> dumped = pickler.dump(btree)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
SystemError: error return without exception set
```

Interestingly enough, other than when trying to pickle them, the btrees don't cause any issues:

```
>>> for key in btree: print repr(key)
...
<InterfaceClass webdav.EtagSupport.EtagBaseInterface>
# ...
# works
```

```
for value in btree.values(): print repr(list(value[1]))
# ...
# works
```

However, when I tried "fix" (re-instantiate) the tree, and then pickle it, it blew up like this:

```
2018-03-16 14:35:40 ERROR ZODB.Connection Couldn't load state for 0x25c00b
Traceback (most recent call last):
  File "/home/zope/eggs/ZODB3-3.10.7-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 860, in setstate
    self._setstate(obj)
  File "/home/zope/eggs/ZODB3-3.10.7-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 901, in _setstate
    p, serial = self._storage.load(obj._p_oid, '')
  File "/home/zope/eggs/ZODB3-3.10.7-py2.7-linux-x86_64.egg/ZEO/ClientStorage.py", line 838, in load
    self._cache.store(oid, tid, None, data)
  File "/home/zope/eggs/ZODB3-3.10.7-py2.7-linux-x86_64.egg/ZEO/cache.py", line 143, in call
    return self.func(inst, *args, **kw)
  File "/home/zope/eggs/ZODB3-3.10.7-py2.7-linux-x86_64.egg/ZEO/cache.py", line 627, in store
    self._store(oid, start_tid, end_tid, data, size)
  File "/home/zope/eggs/ZODB3-3.10.7-py2.7-linux-x86_64.egg/ZEO/cache.py", line 641, in _store
    nfreebytes = self._makeroom(size+1)
  File "/home/zope/eggs/ZODB3-3.10.7-py2.7-linux-x86_64.egg/ZEO/cache.py", line 443, in _makeroom
    del current[oid]
  File "/home/zope/eggs/ZODB3-3.10.7-py2.7-linux-x86_64.egg/ZODB/fsIndex.py", line 147, in __delitem__
    del tree[key[6:]]
KeyError: '\xa8\xd4'
Traceback (most recent call last):
  File "<console>", line 1, in <module>
SystemError: NULL result without error in PyObject_Call
```

This lead me to believe, that the problem might actually be related to a corrupt `Data.fs.index`. So I stopped ZEO, renamed the existing `Data.fs.index` and restartet ZEO to have it regenerated (still on `03-gever-stabs-test`).

That didn't seem to fix the issue though.

Also, this error is intermittent it seems - at first I had this error when simply re-instantiating the new tree and accessing its values. Now that seems to work, but pickling the new (as well as the old) tree still fails.

So at this point I'm not really sure what's going on, and I will change the upgrade step in a way that the actual *check* at least is robust, so it doesn't cause failures during upgrades. These BTrees in BS will then be skipped, but they don't exhibit the specific problem this upgrade step tries to fix anyway (remaining reference to `ICreatorAware` interface).

**Comment by deiferni** [comment]
One approach would be to not attempt to be smart and detect errors in the `BTree` but just re-instantiate them unconditionally 🤔.

**Comment by deiferni** [comment]
As just discussed, we will leave the upgrade disabled as it seems to cause more trouble than it provides value. If the error occurs for another customer we will provide an https://github.com/4teamwork/opengever.maintenance fix-script to solve the issues.
