### ISSUE TITLE
Flaky Tests: OrgUnitSelectorViewlet

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#4098]
There are some flaky tests apparently related to the OrgUnitSelectorViewlet.

Example failure:
https://ci.4teamwork.ch/builds/150234/tasks/237206

*(This build also hat legitimate failures as well though)*

Other failure, on a completely different change:
https://ci.4teamwork.ch/builds/149401/tasks/235765

I feel like these started appearing after #4031 was merged, but that's just a vague guess based on timing.

Tracebacks:

```
Command line

bin/test --layer opengever.core.testing.opengever.core:functional -t opengever.mail.tests.test_message_filename_initialized.TestMessageFilenameInitialized -t opengever.mail.tests.test_ogmail.TestExtractMailInDossier -t opengever.mail.tests.test_ogmail.TestExtractMailInInbox -t opengever.mail.tests.test_ogmail.TestExtractMailInTask -t opengever.mail.tests.test_ogmail.TestOGMailAddition -t opengever.mail.tests.test_senddocument.TestSendDocument -t opengever.mail.tests.test_subscribers.TestSubscribers -t opengever.mail.tests.test_validators.TestFileOrPaperValidatorInEditForm -t opengever.meeting.tests.test_close.TestCloseMeeting -t opengever.meeting.tests.test_committee_roles.TestCommitteeTabs -t opengever.meeting.tests.test_committee_tabs.TestCommitteeTabs -t opengever.meeting.tests.test_download_sablon_template.TestSablonTemplateDownloadView -t opengever.meeting.tests.test_hold.TestHoldMeeting -t opengever.meeting.tests.test_indexers.TestSablonTemplateIndexers -t opengever.meeting.tests.test_meeting_dossier_byline.TestMeetingDossierByline -t opengever.meeting.tests.test_meetingfeature.TestDisabledMeetingFeature -t opengever.meeting.tests.test_member_vocabulary.TestMemberVocabulary -t opengever.meeting.tests.test_pathbar.TestPathBar -t opengever.meeting.tests.test_proposal_template.TestProposalTemplate -t opengever.meeting.tests.test_protocol.TestFormatParticipant -t opengever.meeting.tests.test_protocol_json_data.TestExcerptJsonData -t opengever.meeting.tests.test_protocol_json_data.TestProtocolJsonData -t opengever.officeatwork.tests.test_create_with_officeatwork.TestCreateWithOfficeatworkFeatureDisabled -t opengever.officeatwork.tests.test_feature.TestIsOfficeatworkFeatureEnabled -t opengever.officeatwork.tests.test_feature.TestIsOfficeatworkFeatureEnabledView -t opengever.officeconnector.tests.test_feature.TestIsOfficeConnectorFeatureEnabled -t opengever.officeconnector.tests.test_feature.TestIsOfficeConnectorFeatureEnabledView -t opengever.ogds.base.tests.test_actor_label.TestUserLabel -t opengever.ogds.base.tests.test_cookie_storage.TestCookieStorage -t opengever.ogds.base.tests.test_ogds_updater.TestOGDSUpdater -t opengever.ogds.base.tests.test_plugin.TestRemoteAuthenticationPlugin -t opengever.ogds.base.tests.test_sort_helpers.TestUserSortDict -t opengever.ogds.base.tests.test_sources.TestAllEmailContactsAndUsersSource -t opengever.ogds.base.tests.test_sources.TestAllUsersInboxesAndTeamsSource -t opengever.ogds.base.tests.test_sources.TestAllUsersSource -t opengever.ogds.base.tests.test_sources.TestAssignedUsersSource -t opengever.ogds.base.tests.test_sources.TestContactsSource -t opengever.ogds.base.tests.test_sources.TestUsersContactsInboxesSource -t opengever.ogds.base.tests.test_viewlet_ou_selector.TestOrgUnitSelectorViewlet -t opengever.ogds.base.tests.test_viewlet_ou_selector.TestOrgUnitSelectorViewletIsAvailable -t opengever.ogds.base.tests.test_vocabularies.TestAssignedClientsVocabularies -t opengever.ogds.base.tests.test_vocabularies.TestContactVocabulary -t opengever.ogds.base.tests.test_vocabularies.TestOrgUnitsVocabularyFactory -t opengever.portlets.tree.tests.test_favorites.TestRepositoryFavorites -t opengever.portlets.tree.tests.test_favorites.TestRepositoryFavoritesView -t opengever.portlets.tree.tests.test_treeportlet.TestTreePortlet -t opengever.private.tests.test_dossier.TestPrivateDossierTabbedView -t opengever.private.tests.test_dossier.TestPrivateDossierWorkflow -t opengever.private.tests.test_root.TestPrivateRoot -t opengever.quota.tests.test_primary_field_quota_subject.TestPrimaryFieldQuotaSubject -t opengever.setup.tests.test_creation.TestUnitCreation -t opengever.setup.tests.test_local_role_configuration.TestLocalRoleConfiguration -t opengever.setup.tests.test_opengever_content.TestDocumentTemplates -t opengever.setup.tests.test_repository_creation.TestRepositoryCreation -t opengever.setup.tests.test_unit_creation.TestAdminUnitCreator -t opengever.setup.tests.test_unit_creation.TestOrgUnitCreator -t opengever.sharing.tests.test_sharing_integration.TestOpengeverSharingIntegration -t opengever.tabbedview.tests.test_bumblebee_gallery.TestBaseTabProxyWithDeactivatedFeature -t opengever.tabbedview.tests.test_bumblebee_gallery.TestBumblebeeGalleryMixin -t opengever.tabbedview.tests.test_bumblebee_gallery.TestBumblebeeGalleryMixinFetch -t opengever.tabbedview.tests.test_bumblebee_gallery.TestBumblebeeGalleryViewChooserWithoutFeature -t opengever.tabbedview.tests.test_bumblebee_gallery.TestDocumentsGalleryFetch -t opengever.tabbedview.tests.test_bumblebee_gallery.TestMyDocumentsGalleryFetch -t opengever.tabbedview.tests.test_bumblebee_gallery.TestProxyViewsWithDeactivatedFeature -t opengever.tabbedview.tests.test_dossier_listing.TestDossierListing -t opengever.tabbedview.tests.test_dossier_tasks_tab.TestDossierTaskTabbedview -t opengever.tabbedview.tests.test_sorting.TestSortColumnExists -t opengever.tabbedview.tests.test_sqlsource.TestSQLAlchemySortIndexes -t opengever.tabbedview.tests.test_sqlsource.TestTextFilter -t opengever.tabbedview.tests.test_statestorage.TestGeverGridStateStorageKeyGenerator -t opengever.tabbedview.tests.test_user_listing.TestUserListing -t opengever.task.tests.test_actionmenu_viewlet.TestActionmenuViewlet -t opengever.task.tests.test_assign_to_dossier.TestAssignForwardignToDossier

STDOUT

ftw.testing PATCHING: Products.CMFQuickInstallerTool.events.handleProfileImportedEvent with noop
ftw.testing PATCHING: Products.CMFQuickInstallerTool.events.handleBeforeProfileImportEvent with noop
Running opengever.core.testing.opengever.core:functional tests:
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.z2.Startup in 0.145 seconds.
  Set up plone.app.testing.layers.PloneFixture in 5.475 seconds.
  Set up ftw.testing.layer.ComponentRegistryIsolationLayer in 0.000 seconds.
  Set up ftw.builder.testing.BuilderLayer in 0.000 seconds.
  Set up opengever.core.sqlite_testing.SQLiteMemoryFixture in 0.001 seconds.
  Set up opengever.core.testing.OpengeverFixture:SQLiteMemoryFixture in 10.115 seconds.
  Set up ftw.builder.testing.set_builder_session_factory in 0.000 seconds.
  Set up opengever.core.testing.opengever.core:functional in 0.000 seconds.

ftw.testbrowser dump: /tmp/ftw.testbrowser-M2FySF.html

Failure in test test_active_unit_has_class_active (opengever.ogds.base.tests.test_viewlet_ou_selector.TestOrgUnitSelectorViewlet)
Traceback (most recent call last):
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/var/lib/jenkins/zope/eggs/ftw.testbrowser-1.29.5-py2.7.egg/ftw/testbrowser/__init__.py", line 42, in test_function
    return func(self, *args, **kwargs)
  File "/var/lib/jenkins/jobs/opengever.core-weight-5/workspace/opengever/ogds/base/tests/test_viewlet_ou_selector.py", line 137, in test_active_unit_has_class_active
    self.assertEquals(['Client 1'], units.text)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 742, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 724, in assertSequenceEqual
    self.fail(msg)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: Lists differ: ['Client 1'] != []

First list contains 1 additional elements.
First extra element 0:
'Client 1'

- ['Client 1']
+ []

 
ftw.testbrowser dump: /tmp/ftw.testbrowser-OtZUQ8.html

Failure in test test_active_unit_is_not_linked (opengever.ogds.base.tests.test_viewlet_ou_selector.TestOrgUnitSelectorViewlet)
Traceback (most recent call last):
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/var/lib/jenkins/zope/eggs/ftw.testbrowser-1.29.5-py2.7.egg/ftw/testbrowser/__init__.py", line 42, in test_function
    return func(self, *args, **kwargs)
  File "/var/lib/jenkins/jobs/opengever.core-weight-5/workspace/opengever/ogds/base/tests/test_viewlet_ou_selector.py", line 130, in test_active_unit_is_not_linked
    self.assertEquals(['Client 1'], units.text)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 742, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 724, in assertSequenceEqual
    self.fail(msg)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: Lists differ: ['Client 1'] != []

First list contains 1 additional elements.
First extra element 0:
'Client 1'

- ['Client 1']
+ []

 
ftw.testbrowser dump: /tmp/ftw.testbrowser-_e03L3.html

Failure in test test_first_unit_is_marked_as_active_per_default (opengever.ogds.base.tests.test_viewlet_ou_selector.TestOrgUnitSelectorViewlet)
Traceback (most recent call last):
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/var/lib/jenkins/zope/eggs/ftw.testbrowser-1.29.5-py2.7.egg/ftw/testbrowser/__init__.py", line 42, in test_function
    return func(self, *args, **kwargs)
  File "/var/lib/jenkins/jobs/opengever.core-weight-5/workspace/opengever/ogds/base/tests/test_viewlet_ou_selector.py", line 107, in test_first_unit_is_marked_as_active_per_default
    ['Client 1'], active_unit.text)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 742, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 724, in assertSequenceEqual
    self.fail(msg)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: Lists differ: ['Client 1'] != []

First list contains 1 additional elements.
First extra element 0:
'Client 1'

- ['Client 1']
+ []

 
ftw.testbrowser dump: /tmp/ftw.testbrowser-avFESD.html

Failure in test test_list_all_assigned_units (opengever.ogds.base.tests.test_viewlet_ou_selector.TestOrgUnitSelectorViewlet)
Traceback (most recent call last):
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/var/lib/jenkins/zope/eggs/ftw.testbrowser-1.29.5-py2.7.egg/ftw/testbrowser/__init__.py", line 42, in test_function
    return func(self, *args, **kwargs)
  File "/var/lib/jenkins/jobs/opengever.core-weight-5/workspace/opengever/ogds/base/tests/test_viewlet_ou_selector.py", line 115, in test_list_all_assigned_units
    ['Client 1', 'Client 3', 'Client 4'], units.text)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 742, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 724, in assertSequenceEqual
    self.fail(msg)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: Lists differ: ['Client 1', 'Client 3', 'Clie... != []

First list contains 3 additional elements.
First extra element 0:
'Client 1'

- ['Client 1', 'Client 3', 'Client 4']
+ []

 
ftw.testbrowser dump: /tmp/ftw.testbrowser-9OpHJv.html

Failure in test test_list_only_current_admin_units_org_units (opengever.ogds.base.tests.test_viewlet_ou_selector.TestOrgUnitSelectorViewlet)
Traceback (most recent call last):
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/var/lib/jenkins/zope/eggs/ftw.testbrowser-1.29.5-py2.7.egg/ftw/testbrowser/__init__.py", line 42, in test_function
    return func(self, *args, **kwargs)
  File "/var/lib/jenkins/jobs/opengever.core-weight-5/workspace/opengever/ogds/base/tests/test_viewlet_ou_selector.py", line 123, in test_list_only_current_admin_units_org_units
    ['Client 1', 'Client 3', 'Client 4'], units.text)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 742, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 724, in assertSequenceEqual
    self.fail(msg)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: Lists differ: ['Client 1', 'Client 3', 'Clie... != []

First list contains 3 additional elements.
First extra element 0:
'Client 1'

- ['Client 1', 'Client 3', 'Client 4']
+ []

 
ftw.testbrowser dump: /tmp/ftw.testbrowser-UZhMhN.html

Error in test test_selecting_a_unit_changes_active_unit (opengever.ogds.base.tests.test_viewlet_ou_selector.TestOrgUnitSelectorViewlet)
Traceback (most recent call last):
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/var/lib/jenkins/zope/eggs/ftw.testbrowser-1.29.5-py2.7.egg/ftw/testbrowser/__init__.py", line 42, in test_function
    return func(self, *args, **kwargs)
  File "/var/lib/jenkins/jobs/opengever.core-weight-5/workspace/opengever/ogds/base/tests/test_viewlet_ou_selector.py", line 142, in test_selecting_a_unit_changes_active_unit
    browser.css('.orgunitMenuContent a')[1].click()
IndexError: list index out of range

 
ftw.testbrowser dump: /tmp/ftw.testbrowser-7Gmwq0.html

Failure in test test_units_are_sorted_alphabetically (opengever.ogds.base.tests.test_viewlet_ou_selector.TestOrgUnitSelectorViewlet)
Traceback (most recent call last):
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/var/lib/jenkins/zope/eggs/ftw.testbrowser-1.29.5-py2.7.egg/ftw/testbrowser/__init__.py", line 42, in test_function
    return func(self, *args, **kwargs)
  File "/var/lib/jenkins/jobs/opengever.core-weight-5/workspace/opengever/ogds/base/tests/test_viewlet_ou_selector.py", line 99, in test_units_are_sorted_alphabetically
    ['Client 1', 'Client 3', 'Client 4'], units.text)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 742, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 724, in assertSequenceEqual
    self.fail(msg)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: Lists differ: ['Client 1', 'Client 3', 'Clie... != []

First list contains 3 additional elements.
First extra element 0:
'Client 1'

- ['Client 1', 'Client 3', 'Client 4']
+ []

 
ftw.testbrowser dump: /tmp/ftw.testbrowser-HaSzDC.html

Failure in test test_org_unit_selector_visible_for_multiple_org_units (opengever.ogds.base.tests.test_viewlet_ou_selector.TestOrgUnitSelectorViewletIsAvailable)
Traceback (most recent call last):
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/var/lib/jenkins/zope/eggs/ftw.testbrowser-1.29.5-py2.7.egg/ftw/testbrowser/__init__.py", line 42, in test_function
    return func(self, *args, **kwargs)
  File "/var/lib/jenkins/jobs/opengever.core-weight-5/workspace/opengever/ogds/base/tests/test_viewlet_ou_selector.py", line 45, in test_org_unit_selector_visible_for_multiple_org_units
    self.assertEqual(1, len(browser.css('#portal-orgunit-selector')))
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 0

  Ran 300 tests with 7 failures, 1 errors and 0 skipped in 3 minutes 55.010 seconds.
Tearing down left over layers:
  Tear down opengever.core.testing.opengever.core:functional in 0.000 seconds.
  Tear down opengever.core.testing.OpengeverFixture:SQLiteMemoryFixture in 0.004 seconds.
  Tear down opengever.core.sqlite_testing.SQLiteMemoryFixture in 0.000 seconds.
  Tear down ftw.testing.layer.ComponentRegistryIsolationLayer in 0.000 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.071 seconds.
  Tear down plone.testing.z2.Startup in 0.006 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.002 seconds.
  Tear down ftw.builder.testing.set_builder_session_factory in 0.000 seconds.
  Tear down ftw.builder.testing.BuilderLayer in 0.000 seconds.
```

**Comment by Rotonen** [comment]
Do we just close this at this point?

**Comment by deiferni** [comment]
ok 👍
