### ISSUE TITLE
Tooltip of favorites icon does not appear

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#4353]
**Expected:**
Tooltip on-hover as specified in #4103
![bildschirmfoto 2018-03-13 um 09 41 29](https://user-images.githubusercontent.com/7469/37957450-39f0af2a-31ae-11e8-9e42-c5416e6519dc.png)

**Got:**
Tooltip does not appear.

**Comment by tarnap** [comment]
![tooltip](https://user-images.githubusercontent.com/194114/40671271-b5e70dce-636b-11e8-850d-0c882f3ec732.gif)

Implemented in: https://github.com/4teamwork/opengever.core/tree/pv-tooltip_does_not_appear-4353

Question about the tests: Can this be tested with the test-browser?

**Comment by tarnap** [comment]
Sehr schön:
```
Failure in test test_adds_is_favorite_class_when_favorite_exists (opengever.base.tests.test_favorite_action.TestFavoriteAction)
Traceback (most recent call last):
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/var/lib/jenkins/zope/eggs/ftw.testbrowser-1.29.7-py2.7.egg/ftw/testbrowser/__init__.py", line 42, in test_function
    return func(self, *args, **kwargs)
  File "/var/lib/jenkins/jobs/opengever.core-weight-5/workspace/opengever/base/tests/test_favorite_action.py", line 59, in test_adds_is_favorite_class_when_favorite_exists
    '', browser.css('#mark-as-favorite').first.get('class'))
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/python/2.7.14/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: '' != None
```
Das passiert, das neu der Attribut nicht gesetzt wird wenn das Objekt kein Favorit ist.
Ich schlage vor, hier den Test anzupassen.
