### ISSUE TITLE
Test (isloation?) failures in opengever.meeting

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#4684]
Local quick reproduction with `bin/test -m opengever.meeting`.

```
$ bin/test -m opengever.meeting
ftw.testing PATCHING: Products.CMFQuickInstallerTool.events.handleProfileImportedEvent with noop
ftw.testing PATCHING: Products.CMFQuickInstallerTool.events.handleBeforeProfileImportEvent with noop
Test-module import failures:

Module: opengever.meeting.tests.test_activites

Traceback (most recent call last):
  File "/Users/joni/koodaus/git/opengever.core/opengever/meeting/tests/test_activites.py", line 6, in <module>
    from opengever.meeting.activity.activities import actor_link
  File "/Users/joni/koodaus/git/opengever.core/opengever/meeting/activity/activities.py", line 4, in <module>
    from opengever.meeting.model import Meeting
  File "/Users/joni/koodaus/git/opengever.core/opengever/meeting/model/__init__.py", line 4, in <module>
    from opengever.meeting.model.committee import Committee  # noqa
  File "/Users/joni/koodaus/git/opengever.core/opengever/meeting/model/committee.py", line 10, in <module>
    from opengever.meeting.model.proposal import Proposal
  File "/Users/joni/koodaus/git/opengever.core/opengever/meeting/model/proposal.py", line 7, in <module>
    from opengever.meeting.activity.activities import ProposalDecideActivity
ImportError: cannot import name ProposalDecideActivity


Running ftw.testing.layer.ComponentUnitTesting tests:
  Set up ftw.testing.layer.ftw.testing:LAYER_CLEANUP in 0.000 seconds.
  Set up ftw.testing.layer.ftw.testing:ZCML_DIRECTIVES in 0.003 seconds.
  Set up ftw.testing.layer.ComponentUnitTesting in 0.003 seconds.
  Running:

  Ran 4 tests with 0 failures, 1 errors, 0 skipped in 0.001 seconds.
-- snip --
```

Seems something is up with the `ComponentUnitTesting` layer?

Does not flare up in the CI runs currently.

**Comment by Rotonen** [comment]
Passes with `bin/test -m opengever.document -m opengever.meeting` so at least whatever the document component unit tests do, seems to be what the meeting component unit tests rely on.
