### ISSUE TITLE
Test isolation failure in the zserver layer for opengever.base

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#4724]
```
$ bin/test -m opengever.base
--- snip ---
Failure in test test_document_status_json (opengever.base.tests.test_api.TestBaseDocumentApi)
Traceback (most recent call last):
  File "/Users/joni/.homebrew/var/pyenv/versions/2.7.15/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/joni/koodaus/git/opengever.core/opengever/base/tests/test_api.py", line 73, in test_document_status_json
    self.assertEqual(True, response['checked_out'])
  File "/Users/joni/.homebrew/var/pyenv/versions/2.7.15/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/joni/.homebrew/var/pyenv/versions/2.7.15/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: True != False
--- snip ---
Total: 662 tests, 1 failures, 0 errors, 5 skipped in 6 minutes 47.500 seconds.
```

**Comment by Rotonen** [comment]
Seems to have been resolved by https://github.com/4teamwork/opengever.core/pull/5229
