### ISSUE TITLE
MultiAdminUnit Task completion fails with KeyError

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#6062]
https://sentry.4teamwork.ch/sentry/onegov-gever/issues/3751/

```
RemoteRequestFailed: Remote request to Traceback (most recent call last):
  File "/home/zope/02-gever-digs-test/src/opengever.core/opengever/base/request.py", line 185, in __call__
    return super(SafeCall, self).__call__(*args, **kwargs)
  File "/home/zope/02-gever-digs-test/src/opengever.core/opengever/task/browser/complete.py", line 265, in __call__
    if self.is_already_delivered(data):
  File "/home/zope/02-gever-digs-test/src/opengever.core/opengever/task/browser/complete.py", line 325, in is_already_delivered
    last_response = response_container[-1]
  File "/home/zope/02-gever-digs-test/src/opengever.core/opengever/base/response.py", line 129, in __getitem__
    return storage[long(key)]
KeyError: -1L
(9 additional frame(s) were not displayed)
...
  File "home/zope/eggs/z3c.form-3.2.11-py2.7.egg/z3c/form/button.py", line 170, in __call__
    return self.func(form, action)
  File "src/opengever.core/opengever/task/browser/complete.py", line 138, in handle_save
    self.deliver_documents_and_complete_task(data, response)
  File "src/opengever.core/opengever/task/browser/complete.py", line 235, in deliver_documents_and_complete_task
    data=request_data)
  File "src/opengever.core/opengever/base/request.py", line 82, in dispatch_request
    data, headers)
  File "src/opengever.core/opengever/base/request.py", line 164, in _remote_request
    raise RemoteRequestFailed(url, content)

RemoteRequestFailed: Remote request to "Traceback: Traceback (most recent call last):
  File "/home/zope/02-gever-digs-test/src/opengever.core/opengever/base/request.py", line 185, in __call__
    return super(SafeCall, self).__call__(*args, **kwargs)
  File "/home/zope/02-gever-digs-test/src/opengever.core/opengever/task/browser/complete.py", line 265, in __call__
    if self.is_already_delivered(data):
  File "/home/zope/02-gever-digs-test/src/opengever.core/opengever/task/browser/complete.py", line 325, in is_already_delivered
    last_response = response_container[-1]
  File "/home/zope/02-gever-digs-test/src/opengever.core/opengever/base/response.py", line 129, in __getitem__
    return storage[long(key)]
KeyError: -1L
```

**Comment by phgross** [comment]
Fachliches Review: 👍 bereits durch Erich.
