### ISSUE TITLE
solr indexing issue when creating a document from a template

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#6371]
A similar problem to the one fixed in https://github.com/4teamwork/opengever.core/issues/5547 h has resurfaced (as described in that PR, we never fixed the root cause of this).

Basically when creating a document from a template, under certain circumstances (does not seem to happen on all deployments), solr tries to reindex a blob that is not there anymore, throwing the following error:
```
2020-04-02 19:15:03 ERROR txn.123145440686080 Error in after commit hook exec in <function hook at 0x11bef6230> 
Traceback (most recent call last):
  File "/Users/njohner/.buildout/cache/eggs/transaction-1.1.1-py2.7.egg/transaction/_transaction.py", line 416, in _callAfterCommitHooks
    hook(status, *args, **kws)
  File "/Users/njohner/.buildout/cache/eggs/ftw.solr-2.8.1-py2.7.egg/ftw/solr/connection.py", line 156, in hook
    file_ = blob.committed()
  File "/Users/njohner/.buildout/cache/eggs/ZODB3-3.10.7-py2.7-macosx-10.14-x86_64.egg/ZODB/blob.py", line 202, in committed
    raise BlobError('Uncommitted changes')
BlobError: Uncommitted changes
```

I did not have enough time to analyse this properly, but it would seem that the issue comes from writing the docproperties just after creating the object, this overwrites the blob and as during object creation the blob landed in the indexing queue, when it is then processed, solr cannot find the blob or something like that. 

Proposed fix is in https://github.com/4teamwork/opengever.core/pull/6370, but I didn't have time to write tests. Locally it seems to fix the issue (I did not check whether docproperties actually still get updated correctly)

The problem might have appeared with https://github.com/4teamwork/ftw.solr/pull/149, or not

**Comment by njohner** [comment]
Closed with https://github.com/4teamwork/opengever.core/pull/6370
